'use client'

import { useEffect, useMemo, useState } from 'react'
import { Bell, Check, ChevronDown, Circle, ClipboardList, Clock3, MoreHorizontal, Pencil, Plus, Search, Settings, Sparkles, Trash2, UserRound, X } from 'lucide-react'

type Task = { id: number; title: string; note?: string; category: string; priority: 'High' | 'Medium' | 'Low'; due?: string; reminder?: string; completed: boolean }
type Filter = 'All tasks' | 'Today' | 'Upcoming' | 'Completed'
const starterTasks: Task[] = [
  { id: 1, title: 'Review project brief', note: 'Clarify scope and share feedback with the team.', category: 'Work', priority: 'High', due: 'Today', reminder: '09:30', completed: false },
  { id: 2, title: 'Book dentist appointment', category: 'Personal', priority: 'Medium', due: 'Tomorrow', completed: false },
  { id: 3, title: 'Prepare weekly presentation', note: 'Add the latest product insights and roadmap updates.', category: 'Work', priority: 'High', due: 'Fri, Aug 30', completed: false },
  { id: 4, title: 'Go for a 30-minute walk', category: 'Wellness', priority: 'Low', due: 'Today', completed: true },
]
const filters: Filter[] = ['All tasks', 'Today', 'Upcoming', 'Completed']
const suggestions = ['Plan tomorrow before signing off', 'Clear your inbox for 15 minutes', 'Take a mindful stretch break']

export default function Page() {
  const [tasks, setTasks] = useState<Task[]>(starterTasks); const [filter, setFilter] = useState<Filter>('All tasks'); const [query, setQuery] = useState(''); const [sort, setSort] = useState<'Priority' | 'Due date'>('Priority'); const [editing, setEditing] = useState<Task | null>(null); const [showComposer, setShowComposer] = useState(false); const [showAccount, setShowAccount] = useState(false); const [showMenu, setShowMenu] = useState(false); const [toast, setToast] = useState(''); const [user, setUser] = useState('Alex Morgan');
  useEffect(() => { const saved = window.localStorage.getItem('focus-tasks'); if (saved) setTasks(JSON.parse(saved)) }, []); useEffect(() => { window.localStorage.setItem('focus-tasks', JSON.stringify(tasks)) }, [tasks]); useEffect(() => { if (!toast) return; const t = setTimeout(() => setToast(''), 2800); return () => clearTimeout(t) }, [toast]);
  const visibleTasks = useMemo(() => tasks.filter(t => (t.title + ' ' + (t.note || '')).toLowerCase().includes(query.toLowerCase())).filter(t => filter === 'All tasks' || (filter === 'Completed' ? t.completed : filter === 'Today' ? t.due === 'Today' : t.due !== 'Today' && !t.completed)).sort((a,b) => sort === 'Priority' ? ({High:0,Medium:1,Low:2}[a.priority] - {High:0,Medium:1,Low:2}[b.priority]) : (a.due || '').localeCompare(b.due || '')), [tasks, filter, query, sort]);
  const completed = tasks.filter(t => t.completed).length; const progress = tasks.length ? Math.round(completed / tasks.length * 100) : 0;
  function createTask(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const title = String(f.get('title') || '').trim(); if (!title) return; setTasks(c => [{ id: Date.now(), title, note: String(f.get('note') || ''), category: String(f.get('category') || 'Personal'), priority: f.get('priority') as Task['priority'], due: String(f.get('due') || 'Today'), reminder: String(f.get('reminder') || ''), completed: false }, ...c]); setShowComposer(false); setToast('Task added to your focus list.'); }
  function saveEdit(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); if (!editing) return; const f = new FormData(e.currentTarget); setTasks(c => c.map(t => t.id === editing.id ? {...t, title: String(f.get('title')), note: String(f.get('note')), category: String(f.get('category')), priority: f.get('priority') as Task['priority'], due: String(f.get('due')), reminder: String(f.get('reminder'))} : t)); setEditing(null); setToast('Task details updated.'); }
  function remind(task: Task) { if ('Notification' in window && Notification.permission === 'granted') new Notification(`Reminder: ${task.title}`); else if ('Notification' in window && Notification.permission !== 'denied') Notification.requestPermission().then(p => p === 'granted' ? new Notification(`Reminder: ${task.title}`) : setToast('Notifications are blocked. Reminder saved for ' + (task.reminder || 'later') + '.')); else setToast('Reminder saved for ' + (task.reminder || 'later') + '.'); }
  function addSuggestion(title: string) { setTasks(c => [{id: Date.now(), title, category:'Wellness', priority:'Low', due:'Today', completed:false}, ...c]); setToast('Suggestion added as a task.'); }
  return <main className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark"><Sparkles size={15}/></span><span>focus<span className="brand-dot">.</span></span></div><button className="profile" onClick={() => setShowAccount(true)}><div className="avatar">{user.split(' ').map(x=>x[0]).join('')}</div><div><strong>{user}</strong><span>Personal workspace</span></div><ChevronDown size={15}/></button><nav aria-label="Task filters"><p className="nav-label">Workspace</p>{filters.map((item,i)=><button key={item} className={`nav-item ${filter===item?'active':''}`} onClick={()=>setFilter(item)}><span className="nav-icon">{i===0?<ClipboardList size={17}/>:i===1?<Circle size={14}/>:i===2?<Sparkles size={16}/>:<Check size={17}/>}</span>{item}<span className="count">{i===0?tasks.filter(t=>!t.completed).length:i===3?completed:''}</span></button>)}</nav><div className="sidebar-bottom"><div className="streak"><span className="streak-icon">✦</span><div><strong>4 day streak</strong><span>Small steps, big momentum.</span></div></div><button className="settings-link" onClick={()=>setToast('Settings are ready for your next session.')}><Settings size={16}/> Settings</button></div></aside>
  <section className="content"><header className="topbar"><div className="breadcrumb">Workspace <span>/</span> <strong>Tasks</strong></div><div className="top-actions"><div className="search"><Search size={17}/><input aria-label="Search tasks" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search tasks"/><kbd>⌘ K</kbd></div><button className="icon-button" aria-label="More options" onClick={()=>setShowMenu(!showMenu)}><MoreHorizontal size={20}/></button><button className="avatar small" aria-label="Open account" onClick={()=>setShowAccount(true)}>{user.split(' ').map(x=>x[0]).join('')}</button>{showMenu&&<div className="popover"><button onClick={()=>{setSort(sort==='Priority'?'Due date':'Priority');setShowMenu(false)}}>Sort by {sort==='Priority'?'due date':'priority'}</button><button onClick={()=>{setQuery('');setShowMenu(false)}}>Clear search</button></div>}</div></header><div className="page-heading"><div><p className="eyebrow">Tuesday, August 27, 2026</p><h1>Good morning, {user.split(' ')[0]}<span className="heading-dot">.</span></h1><p className="subtitle">Make today count. One task at a time.</p></div><button className="primary-button" onClick={()=>setShowComposer(true)}><Plus size={18}/> New task</button></div>
  <div className="overview-grid"><div className="progress-card"><div className="card-heading"><div><p className="card-kicker">Today&apos;s progress</p><strong>{completed} of {tasks.length} tasks complete</strong></div><span className="progress-number">{progress}%</span></div><div className="progress-track"><span style={{width:`${progress}%`}}/></div><p className="muted-copy">You&apos;re making solid progress. Keep the momentum going.</p></div><div className="stat-card"><span className="stat-icon lime"><Check size={18}/></span><div><strong>{tasks.filter(t=>!t.completed).length}</strong><span>Open tasks</span></div></div><div className="stat-card"><span className="stat-icon coral"><Sparkles size={18}/></span><div><strong>{tasks.filter(t=>t.priority==='High'&&!t.completed).length}</strong><span>High priority</span></div></div></div>
  <section className="experience-zone"><div><p className="card-kicker">Experience zone</p><h2>Design your best day</h2><p>Choose one tiny action to protect your attention and build momentum.</p></div><div className="suggestions">{suggestions.map(s=><button key={s} onClick={()=>addSuggestion(s)}><Sparkles size={15}/>{s}<Plus size={15}/></button>)}</div></section>
  <div className="task-toolbar"><div><h2>{filter}</h2><span className="task-count">{visibleTasks.length} {visibleTasks.length===1?'task':'tasks'}</span></div><button className="sort-button" onClick={()=>setSort(sort==='Priority'?'Due date':'Priority')}>Sort by <strong>{sort}</strong><ChevronDown size={15}/></button></div><div className="task-list">{visibleTasks.length===0?<div className="empty-state"><ClipboardList size={28}/><h3>No tasks here</h3><p>Try another filter or add a new task.</p></div>:visibleTasks.map(task=><article className={`task-row ${task.completed?'is-complete':''}`} key={task.id}><button className={`check-button ${task.completed?'checked':''}`} onClick={()=>setTasks(c=>c.map(t=>t.id===task.id?{...t,completed:!t.completed}:t))} aria-label={`Mark ${task.title} ${task.completed?'incomplete':'complete'}`}>{task.completed&&<Check size={15}/>}</button><div className="task-info"><h3>{task.title}</h3>{task.note&&<p>{task.note}</p>}<div className="task-meta"><span className={`tag ${task.category.toLowerCase()}`}>{task.category}</span><span className={`priority ${task.priority.toLowerCase()}`}><span/>{task.priority}</span>{task.due&&<span className="due">{task.due}</span>}{task.reminder&&<span className="reminder"><Clock3 size={12}/>{task.reminder}</span>}</div></div><div className="task-actions"><button onClick={()=>remind(task)} aria-label={`Remind me about ${task.title}`}><Bell size={16}/></button><button onClick={()=>setEditing(task)} aria-label={`Edit ${task.title}`}><Pencil size={16}/></button><button onClick={()=>{setTasks(c=>c.filter(t=>t.id!==task.id));setToast('Task deleted.')}} aria-label={`Delete ${task.title}`}><Trash2 size={16}/></button></div></article>)}</div><footer className="footer-note"><span className="live-dot"/> Changes are saved automatically <span className="footer-separator">•</span> {tasks.length} total tasks</footer></section>
  {(showComposer||editing)&&<div className="modal-backdrop" onMouseDown={()=>{setShowComposer(false);setEditing(null)}}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>{setShowComposer(false);setEditing(null)}} aria-label="Close"><X size={18}/></button><p className="eyebrow">{editing?'Edit task':'New task'}</p><h2>{editing?'Refine your task':'What needs your focus?'}</h2><form onSubmit={editing?saveEdit:createTask}><input name="title" defaultValue={editing?.title} placeholder="Task title" autoFocus required/><textarea name="note" defaultValue={editing?.note} placeholder="Add a helpful note (optional)"/><div className="form-grid"><select name="category" defaultValue={editing?.category||'Personal'}><option>Personal</option><option>Work</option><option>Wellness</option></select><select name="priority" defaultValue={editing?.priority||'Medium'}><option>High</option><option>Medium</option><option>Low</option></select><input name="due" defaultValue={editing?.due||'Today'} placeholder="Due date"/><input name="reminder" defaultValue={editing?.reminder||''} placeholder="Reminder time"/></div><button className="primary-button" type="submit">{editing?'Save changes':'Add task'} <Plus size={17}/></button></form></div></div>}
  {showAccount&&<div className="modal-backdrop" onMouseDown={()=>setShowAccount(false)}><div className="modal account-modal" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setShowAccount(false)} aria-label="Close"><X size={18}/></button><span className="account-icon"><UserRound size={22}/></span><p className="eyebrow">Your focus account</p><h2>Log in or register</h2><p className="modal-copy">Save your workspace identity and make your planning ritual feel like yours.</p><input placeholder="Email address" type="email"/><input placeholder="Password" type="password"/><div className="account-actions"><button className="primary-button" onClick={()=>{setUser('Alex Morgan');setShowAccount(false);setToast('Welcome back, Alex.')}}>Log in</button><button className="secondary-button" onClick={()=>{setUser('New Member');setShowAccount(false);setToast('Your local account is ready.')}}>Register</button></div></div></div>}
  {toast&&<div className="toast" role="status"><Check size={16}/>{toast}</div>}</main>
}
